version: '3'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "${APACHE_PORT:-80}:80"  # Use APACHE_PORT if set, otherwise default to 80
    volumes:
      - .:/var/www/html
    # Add environment variables if needed
    # environment:
    #   - VARIABLE_NAME=value