version: '3'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APACHE_PORT}:80"  # Use the environment variable
    volumes:
      - .:/var/www/html
    # Add environment variables if needed
    # environment:
    #   - VARIABLE_NAME=value